### PR TITLE
Styling using Bootstrap

### PR DESCRIPTION
**Pull request by ManicJamie**
I'm rather tentative about going all in on a styling pass before things like the single-game series entries & multiworld reference links are decided on, but a start is always good.

Partially addresses #5

### CODE REVIEW

**Comment by Die4Ever** [comment]
looking great!

image

image

whenever you mark this as ready I can merge it

**Comment by SmashManiac** [comment]
I like the design, but it seems overkill to me to be importing Bootstrap and adding a bunch of JavaScript just for this one toggle, instead of a pure CSS solution without the toggle.

If people more familiar with front-end development think it's worth it anyway I'm fine with the change.

**Comment by Die4Ever** [comment]
> I like the design, but it seems overkill to me to be importing Bootstrap and adding a bunch of JavaScript just for this one toggle, instead of a pure CSS solution without the toggle.
> 
> If people more familiar with front-end development think it's worth it anyway I'm fine with the change.

I think if we ever expect anyone to contribute then we're gonna have to use bootstrap. Otherwise a new contributor would have to learn how we do things and that'll probably be too big a barrier

**Comment by ManicJamie** [comment]
> ...it seems overkill to me to be importing Bootstrap and adding a bunch of JavaScript just for this one toggle, instead of a pure CSS solution without the toggle.

We bring Bootstrap anyway mainly because the stylesheets would get rather unwieldy very quickly. Not adding the toggle is an option, and would drastically simplify the js, as below;
```js
let theme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
document.documentElement.setAttribute('data-bs-theme', theme);
```
but I'm not sure I like forcing the site to a user's OS/browser setting - there are some sites I personally prefer to use light theme for even if I use dark everywhere else.

**Comment by SmashManiac** [comment]
Alright, sounds good to me then! The current code looks OK in my review as well!

**Comment by ManicJamie** [comment]
Mostly OK but some minor issues that might want to be ironed out;

- Recents list shows lines between every rando - I'd like to have lines only per-date, but as of right now the generation seems to disallow that option, or at the very least make implementing it messy.
- Collapse button could be replaced with a collapse chevron - if series in the full list are made collapsible then should probably have a button "Collapse All" > "Expand All" in the header, but chevrons per-entry are a must.

This is probably ready to merge though, since most of the other styling tweaks I can think of would best be accompanied with structural or generation changes.

**Comment by duncathan** [comment]
> I think if we ever expect anyone to contribute then we're gonna have to use bootstrap. Otherwise a new contributor would have to learn how we do things and that'll probably be too big a barrier

I agree. Bootstrap is a useful lingua franca of sorts. Much more maintainable for an open source site like this where contributors will come and go than any sort of custom pure CSS solution would be

**Pull request merged**
